name: 'Task Definition Otel Sidecar'
description: 'It does magic with JSON.'

inputs:
  task-definition:
    description: 'Task definition'
    required: true
  container-name:
    description: 'Container name'
    required: true
  image:
    description: 'Docker image'
    required: true

outputs:
  task-definition:
    description: 'The modified task defintion.'
    value: ${{ steps.run-python.outputs.task-definition }}

runs:
  using: 'composite'
  steps:
    - name: Set python3
      uses: actions/setup-python@v5
      with:
        python-version-file: '${{ github.action_path }}/src/.python-version'

    - name: Run Python script
      id: run-python
      shell: bash
      run: |
        python3 ${{ github.action_path }}/src/action.py \
          --task-definition "${{ inputs.task-definition }}" \
          --container-name "${{ inputs.container-name }}" \
          --image "${{ inputs.image }}"
