name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: src/.python-version

      - name: Install dependencies
        working-directory: src
        run: |
          python -m pip install --upgrade pip

      - name: Test with pytest
        working-directory: src
        run: |
          pip install pytest pytest-cov
          pytest

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          task-definition: 'example/task-definition.json'

      - name: Print Output
        id: output
        run: |
          cat "${{ steps.test-action.outputs.task-definition }}" | jq '.'
