name: Example workflow using our action
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Python action
        id: python-action
        uses: karelbemelmans/task-definition-otel-sidecar@main
        with:
          task-definition: 'example/task-definition.json'

      - name: Show generated task definition
        run: |
          apt-get install jq -y
          echo "file: ${{ steps.python-action.outputs.task-definition }}"
          cat ${{ steps.python-action.outputs.task-definition }} | jq '.'
